astrolift_version = 1
name = "conflict-quake-mysql"

[app]
slug = "conflict-quake-mysql"
display_name = "Seismic on Aurora MySQL"

[environments.production]

[[workloads]]
name = "web"
kind = "deployment"
replicas = 1
is_public = true
cpu_request = "100m"
cpu_limit = "500m"
memory_request = "192Mi"
memory_limit = "384Mi"

[[workloads.containers]]
name = "web"
is_primary = true
port = 8080

[workloads.containers.healthcheck]
kind = "http"
value = "/health"
port = 8080

[workloads.containers.env]
PYTHONUNBUFFERED = "1"
DB_CONNECT_TIMEOUT = "45"

[[managed_services]]
kind = "mysql"
name = "quakes"
variant = "aurora_mysql_serverless_v2"
size = "small"

[managed_services.extensions]
min_acu = 0
max_acu = 2
seconds_until_auto_pause = 300
engine_version = "8.0.mysql_aurora.3.08.2"

[ingress]
class = "alb"

[ingress.auth]
kind = "oidc"
auth_proxy_host = "auth.astro.conflict.cloud"
discovery_url = "https://cognito-idp.us-west-2.amazonaws.com/us-west-2_xU96Y7DAg/.well-known/openid-configuration"
client_id = "1unkru25uqbon23mnhj2cpv3hd"
